---
title: "Latihan"
author: "Tri Ananda Marpaung"
date: "2026-08-25"
output: html_document
---
```{r}
#install.packages("forecast")
#install.packages("graphics")
#install.packages("TTR")
#install.packages("TSA")
```

```{r}
library("forecast")
```

```{r}
library("graphics")
library("TTR")
```
```{r}
library("TSA")
```
```{r}
library(rio) 
```
```{r}
data1 <- import("C:/Users/Dewi Lestari Natalia/AppData/Local/Packages/5319275A.WhatsAppDesktop_cv1g1gvanyjgm/LocalState/sessions/8028924777222397EF65501973E74F6B0D2B3205/transfers/2026-34/PM25_Anggota_5.xlsx")
head(data1)
```
```{r}
View(data1)
str(data1)
```
```{r}
dim(data1)
```
```{r}
head(data)
str(data)
```





```{r}
names(data)
```
```{r}
head(data, 10)
```

```{r}
data1 <- data[-c(1:3), ]
```

```{r}
data1$`...3` <- as.numeric(data1$`...3`)
```
```{r}
head(data1)
```

```{r}
data1.ts <- ts(data1$`...3`)

data1.ts
```
```{r}
data1.ts <- ts(data1$`...3`)

data1.ts
```
```{r}
summary(data1.ts)
```
```{r}
ts.plot(data1.ts, xlab="Time Period ", ylab="Reading", 
        main = "Time Series Plot")
points(data1.ts)
```

```{r}
install.packages("forecast")
library(forecast)
```
```{r}
# Mengubah data PM2.5 menjadi time series
data1.ts <- ts(data1$`...3`)

# Melihat data time series
data1.ts

# Membuat plot time series
ts.plot(data1.ts,
        xlab = "Time Period",
        ylab = "PM2.5 (ug/m3)",
        main = "Time Series Plot PM2.5")

# Menambahkan titik observasi
points(data1.ts)
```
#Single Moving Average & Double Moving Average

#Pembagian Data
Pembagian data latih dan data uji dilakukan dengan perbandingan 80% data latih dan 20% data uji.

```{r}
# hitung jumlah data
n <- nrow(data1)

# tentukan batas 80%
n_train <- floor(0.8 * n)

# bagi data
training_ma <- data1[1:n_train, ]
testing_ma  <- data1[(n_train+1):n, ]

# ubah ke time series
train_ma.ts <- ts(training_ma$Sales)
test_ma.ts  <- ts(testing_ma$Sales)
```
```{r}
#eksplorasi keseluruhan data
plot(data1.ts, col="red",main="Plot semua data")
points(data1.ts)
```

```{r}
library(ggplot2)

data1_plot <- data.frame(
  Period = 1:length(data1.ts),
  PM25 = as.numeric(data1.ts)
)

head(data1_plot)
```
```{r}
n <- length(data1.ts)

n_train <- floor(0.8 * n)

training_ma <- data1_plot[1:n_train, ]
testing_ma <- data1_plot[(n_train + 1):n, ]
```
```{r}
n <- length(data1.ts)

n_train <- floor(0.8 * n)

n
n_train
n - n_train
```
```{r}
data_plot <- data.frame(
  Period = 1:length(data1.ts),
  PM25 = as.numeric(data1.ts)
)

training_ma <- data_plot[1:n_train, ]

testing_ma <- data_plot[(n_train + 1):n, ]

nrow(training_ma)
nrow(testing_ma)
```
```{r}
#eksplorasi data latih
plot(train_ma.ts, col="blue",main="Plot data latih")
points(train_ma.ts)
```
```{r}
# Membuat time series data uji
test_ma.ts <- ts(
  testing_ma$PM25,
  start = 125,
  frequency = 1
)

# Eksplorasi data uji
plot(test_ma.ts,
     col = "blue",
     main = "Plot Data Uji PM2.5",
     xlab = "Periode Waktu",
     ylab = "PM2.5 (ug/m3)")

points(test_ma.ts)
```
```{r}
library(ggplot2)
```

```{r}
ggplot() + 
  geom_line(
    data = training_ma,
    aes(x = Period, y = PM25, col = "Data Latih")
  ) +
  geom_line(
    data = testing_ma,
    aes(x = Period, y = PM25, col = "Data Uji")
  ) +
  labs(
    x = "Periode Waktu",
    y = "PM2.5 (ug/m3)",
    color = "Legend"
  ) +
  scale_colour_manual(
    name = "Keterangan:",
    breaks = c("Data Latih", "Data Uji"),
    values = c("blue", "red")
  ) + 
  theme_bw() + 
  theme(
    legend.position = "bottom",
    plot.caption = element_text(hjust = 0.5, size = 12)
  )
```
#Single Moving Average (SMA)

```{r}
install.packages("TTR", dependencies = TRUE)
```
```{r}
library(TTR)
```
```{r}
SMA
```
```{r}
data.sma <- SMA(train_ma.ts, n = 6)
```
```{r}
data.sma <- TTR::SMA(train_ma.ts, n = 6)

data.sma
```
```{r}
data.sma <- c(NA, data.sma)

data.sma
```
```{r}
plot(train_ma.ts,
     type = "l",
     main = "SMA dan Ramalan 1 Periode ke Depan",
     xlab = "Periode Waktu",
     ylab = "PM2.5 (ug/m3)")

lines(data.ramal, col = "blue")
```
```{r}
length(train_ma.ts)
```
```{r}
library(TTR)

data.sma <- SMA(train_ma.ts, n = 6)
```
```{r}
data.sma
```
```{r}
data.ramal <- c(NA, data.sma)
data.ramal
```

```{r}
length(data.ramal)
```
```{r}
pemulusan_uji <- tail(data.sma, 32)
```

```{r}
length(data.sma)
length(data.ramal)
```
```{r}
# Data aktual
aktual <- c(data1.ts)

# Forecast 24 periode ke depan
ramalan <- rep(tail(data.sma, 1), 24)

# Gabungkan
data.gab <- cbind(
  aktual = c(aktual, rep(NA, 24)),
  pemulusan = c(data.sma, rep(NA, 24)),
  ramalan = c(rep(NA, length(aktual)), ramalan)
)

data.gab
```

```{r}
data.gab
```
```{r}
ts.plot(data1.ts,
        xlab = "Time Period",
        ylab = "Sales",
        main = "SMA N=6 Data Sales")

points(data1.ts)

lines(data.gab[,2],
      col = "green",
      lwd = 2)

lines(data.gab[,3],
      col = "red",
      lwd = 2)

legend("topleft",
       c("Data Aktual", "Data Pemulusan", "Data Peramalan"),
       lty = 8,
       col = c("black", "green", "red"),
       cex = 0.5)
```

```{r}
error_train.sma <- train_ma.ts - data.sma[1:length(train_ma.ts)]

SSE_train.sma <- sum(error_train.sma[6:length(train_ma.ts)]^2)

MSE_train.sma <- mean(error_train.sma[6:length(train_ma.ts)]^2)

MAPE_train.sma <- mean(
  abs(
    (error_train.sma[6:length(train_ma.ts)] /
       train_ma.ts[6:length(train_ma.ts)]) * 100
  )
)

akurasi_train.sma <- matrix(
  c(SSE_train.sma, MSE_train.sma, MAPE_train.sma
  ),
  nrow = 3
)

row.names(akurasi_train.sma) <- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.sma) <- c("Akurasi m = 6")

akurasi_train.sma
```
```{r}
# Menghitung nilai keakuratan data uji SMA
error_test.sma = test_ma.ts - data.gab[133:156, 3]

# Menghitung SSE
SSE_test.sma = sum(error_test.sma^2)

# Menghitung MSE
MSE_test.sma = mean(error_test.sma^2)

# Menghitung MAPE
MAPE_test.sma = mean(abs((error_test.sma / test_ma.ts) * 100))

# Membuat tabel akurasi
akurasi_test.sma <- matrix(
  c(SSE_test.sma, MSE_test.sma, MAPE_test.sma)
)

row.names(akurasi_test.sma) <- c("SSE", "MSE", "MAPE")
colnames(akurasi_test.sma) <- c("Akurasi m = 6")

akurasi_test.sma
```
#Double Moving Average(DMA)

```{r}
dma <- SMA(data.sma, n = 6)
At <- 2*data.sma - dma
Bt <- 2/(4-1)*(data.sma - dma)
data.dma<- At+Bt
data.ramal2<- c(NA, data.dma)

t = 1:24
f = c()

for (i in t) {
  f[i] = At[length(At)] + Bt[length(Bt)]*(i)
}

data.gab <- cbind(aktual = c(data1.ts), 
                   pemulusan1 = c(data.sma,rep(NA,24)),
                   pemulusan2 = c(dma, rep(NA,24)),
                   At = c(At, rep(NA,24)), 
                   Bt = c(Bt,rep(NA,24)),
                   ramalan = c(data.ramal2, f[-1]))
data.gab
```
```{r}
ts.plot(data1.ts,
        xlab = "Time Period",
        ylab = "Sales",
        main = "DMA N=6 Data Sales")
```
```{r}
ts.plot(data1.ts,
        xlab = "Periode Waktu",
        ylab = "PM2.5 (ug/m3)",
        main = "DMA N=4 Data PM2.5")

points(data1.ts)

lines(data.gab[,3],
      col = "green",
      lwd = 2)

lines(data.gab[,6],
      col = "red",
      lwd = 2)

legend("topleft",
       c("Data aktual", "Data pemulusan", "Data peramalan"),
       lty = 8,
       col = c("black", "green", "red"),
       cex = 0.8)
```
```{r}
install.packages("TTR")
```
```{r}
library(TTR)
```

```{r}
ls()

```
```{r}
names(data)
```
```{r}
train_ma.ts <- data1.ts[1:124]

test_ma.ts <- data1.ts[125:156]
```

```{r}
length(train_ma.ts)
length(test_ma.ts)
```

```{r}
data.sma <- SMA(train_ma.ts, n = 4)

dma <- SMA(data.sma, n = 4)

At <- 2 * data.sma - dma

Bt <- 2 / (4 - 1) * (data.sma - dma)

data.dma <- At + Bt

data.ramal2 <- c(NA, data.dma)
```
```{r}
error_train.dma = train_ma.ts - data.ramal2[1:length(train_ma.ts)]

SSE_train.dma = sum(error_train.dma[8:length(train_ma.ts)]^2)

MSE_train.dma = mean(error_train.dma[8:length(train_ma.ts)]^2)

MAPE_train.dma = mean(
  abs(
    (error_train.dma[8:length(train_ma.ts)] /
     train_ma.ts[8:length(train_ma.ts)]) * 100
  )
)

akurasi_train.dma <- matrix(
  c(SSE_train.dma,
    MSE_train.dma,
    MAPE_train.dma)
)

row.names(akurasi_train.dma) <- c("SSE", "MSE", "MAPE")

colnames(akurasi_train.dma) <- c("Akurasi m = 4")

akurasi_train.dma
```
```{r}
library(TTR)

data.sma <- SMA(train_ma.ts, n = 4)

dma <- SMA(data.sma, n = 4)

At <- 2 * data.sma - dma

Bt <- 2 / (4 - 1) * (data.sma - dma)

data.dma <- At + Bt

data.ramal2 <- c(NA, data.dma)
```

```{r}
t <- 1:32
f <- c()

for (i in t) {
  f[i] = At[length(At)] + Bt[length(Bt)] * i
}
```

```{r}
data.gab2 <- cbind(
  aktual = c(data1.ts),
  pemulusan1 = c(data.sma, rep(NA, 32)),
  pemulusan2 = c(dma, rep(NA, 32)),
  At = c(At, rep(NA, 32)),
  Bt = c(Bt, rep(NA, 32)),
  ramalan = c(data.ramal2, f[-1])
)

data.gab2
```
```{r}
error_test.dma = test_ma.ts - data.gab2[125:156,6]

SSE_test.dma = sum(error_test.dma^2)

MSE_test.dma = mean(error_test.dma^2)

MAPE_test.dma = mean(
  abs((error_test.dma / test_ma.ts) * 100)
)

akurasi_test.dma <- matrix(
  c(SSE_test.dma,
    MSE_test.dma,
    MAPE_test.dma)
)

row.names(akurasi_test.dma) <- c("SSE", "MSE", "MAPE")

colnames(akurasi_test.dma) <- c("Akurasi m = 4")

akurasi_test.dma
```
#Single Exponential Smoothing & Double Exponential Smoothing

```{r}
# jumlah data
n <- length(data1.ts)

# hitung batas 80%
n_train <- floor(0.8 * n)

# bagi data menjadi training dan testing
train_ma.ts <- data1.ts[1:n_train]
test_ma.ts <- data1.ts[(n_train + 1):n]

# cek jumlah data
length(train_ma.ts)
length(test_ma.ts)
```
```{r}
library(TTR)

data.sma <- SMA(train_ma.ts, n = 4)

dma <- SMA(data.sma, n = 4)

At <- 2 * data.sma - dma

Bt <- 2 / (4 - 1) * (data.sma - dma)

data.dma <- At + Bt

data.ramal2 <- c(NA, data.dma)
```

```{r}
error_train.dma = train_ma.ts - data.ramal2[1:length(train_ma.ts)]

SSE_train.dma = sum(error_train.dma[8:length(train_ma.ts)]^2)

MSE_train.dma = mean(error_train.dma[8:length(train_ma.ts)]^2)

MAPE_train.dma = mean(
  abs(
    (error_train.dma[8:length(train_ma.ts)] /
     train_ma.ts[8:length(train_ma.ts)]) * 100
  )
)

akurasi_train.dma <- matrix(
  c(SSE_train.dma,
    MSE_train.dma,
    MAPE_train.dma)
)

row.names(akurasi_train.dma) <- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.dma) <- c("Akurasi m = 4")

akurasi_train.dma
```
```{r}
# Eksplorasi data
plot(data1.ts, col = "black", main = "Plot semua data")
points(data1.ts)
```

```{r}
plot(train_ma.ts,
     col = "red",
     main = "Plot Data Latih")

points(train_ma.ts)
```

```{r}
plot(test_ma.ts,
     col = "blue",
     main = "Plot Data Uji")

points(test_ma.ts)
```
```{r}
n <- length(data1.ts)

n_train <- floor(0.8 * n)

training <- data.frame(
  Periode = 1:n_train,
  Yt = as.numeric(data1.ts[1:n_train])
)

testing <- data.frame(
  Periode = (n_train + 1):n,
  Yt = as.numeric(data1.ts[(n_train + 1):n])
)
```

```{r}
library(ggplot2)

ggplot() + 
  geom_line(
    data = training,
    aes(x = Periode, y = Yt, col = "Data Latih")
  ) +
  geom_line(
    data = testing,
    aes(x = Periode, y = Yt, col = "Data Uji")
  ) +
  labs(
    x = "Periode Waktu",
    y = "PM2.5 (ug/m3)",
    color = "Legend"
  ) +
  scale_colour_manual(
    name = "Keterangan:",
    breaks = c("Data Latih", "Data Uji"),
    values = c("blue", "red")
  ) + 
  theme_bw() +
  theme(
    legend.position = "bottom"
  )
```
#Single Exponential Smoothing
```{r}
train_ma.ts
```
```{r}
library(forecast)

ses.1 <- ses(train_ma.ts, h = 10, alpha = 0.2)

plot(ses.1)
```

```{r}
forecast::ses(train_ma.ts, h = 10, alpha = 0.2)
```

```{r}
install.packages("forecast")  # cukup sekali saja
library(forecast)
```
```{r}
data.ts <- ts(data)
```

```{r}
sum(is.na(train.ts))
```

```{r}
sum(is.nan(train.ts))
```
```{r}
sum(is.infinite(train.ts))
```
```{r}
which(is.na(train.ts))
```
```{r}
which(is.infinite(train.ts))
```
```{r}
train.ts
```
```{r}
train.ts.clean <- na.omit(train.ts)
```
```{r}
HWopt <- HoltWinters(train.ts.clean, beta = FALSE, gamma = FALSE)
HWopt
```
```{r}
plot(HWopt)
```

```{r}

```

